//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SandboxServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SandboxServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAP.Services.Resources.SandboxServiceResource", typeof(SandboxServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON nie jest poprawny!.
        /// </summary>
        internal static string IncorrectJson {
            get {
                return ResourceManager.GetString("IncorrectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api.php.
        /// </summary>
        internal static string SandboxApi {
            get {
                return ResourceManager.GetString("SandboxApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?{0}={1}.
        /// </summary>
        internal static string SandboxApiGetRequest {
            get {
                return ResourceManager.GetString("SandboxApiGetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /info.php.
        /// </summary>
        internal static string SandboxApiInfo {
            get {
                return ResourceManager.GetString("SandboxApiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.88.232/{0}.
        /// </summary>
        internal static string SandboxApiPattern {
            get {
                return ResourceManager.GetString("SandboxApiPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /token.php.
        /// </summary>
        internal static string SandboxApiToken {
            get {
                return ResourceManager.GetString("SandboxApiToken", resourceCulture);
            }
        }
    }
}
